version: '3.8'

services:
  api:
    build: 
      context: .  # Корінь проєкту
      dockerfile: Dockerfile
    ports:
      - "8082:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=PersonDb;Username=postgres;Password=password"
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: postgres:15
    environment: 
      POSTGRES_DB: PersonDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "8084:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Використовуємо nginx.conf з поточної директорії
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  pgdata:
    driver: local

