version: '3.8'

services:
  api:
    build: 
      context: . # Корінь проекту
      dockerfile: Dockerfile
    ports:
      - "8082:80"  # Порт для доступу до API
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=PersonDb;Username=postgres;Password=password"  # Повна рядка з підключенням до бази даних
    depends_on:
      - db  # Залежність від бази даних
    networks:
      - app_network  # Вказано правильну мережу

  db:
    image: postgres:15  # Використовуємо офіційний образ Postgres
    environment:      
      POSTGRES_DB: PersonDb  # База даних
      POSTGRES_USER: postgres  # Користувач
      POSTGRES_PASSWORD: password  # Пароль
    ports:
      - "5432:5432"  # Порт для доступу до бази даних
    volumes:
      - pgdata:/var/lib/postgresql/data  # Том для зберігання даних
    networks:
      - app_network  # Вказано правильну мережу

  nginx:
    image: nginx:latest  # Використовуємо останню версію Nginx
    ports:
      - "8083:80"  # Порт для доступу через Nginx
    volumes:
       - /tmp/jenkins-nginx/nginx.conf:/etc/nginx/nginx.conf:ro
 # - /tmp/jenkins-nginx/nginx.conf:/etc/nginx/nginx.conf:ro
     # - /var/lib/jenkins/workspace/DotnetApiPostgres/nginx.conf:/etc/nginx/nginx.conf:ro
     # - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Маунтимо конфігураційний файл nginx.conf
    depends_on:
      - api  # Nginx залежить від API
    networks:
      - app_network  # Вказано правильну мережу

volumes:
  pgdata:  # Том для бази даних

networks:
  app_network:
    driver: bridge  # Мережа для комунікації між контейнерами

