version: '3.8'

services:
  api:
    build: 
      context: . # Корінь проекту
      dockerfile: Dockerfile
    ports:
#      - "8081:80"
      - "8082:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=PersonDb;Username=postgres;Password=password"
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: PersonDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

